modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="the_new_end_update__forge"
version="0.0.1"
displayName="The New End Update (1.18.2 Forge)"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="vze3h & GibusRat"

[[dependencies.the_new_end_update__forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




